In [3]:
import numpy as np
stock_prices=np.random.randint(100,500,(30,5))


In [5]:
print(np.average(stock_prices,axis=0))
max=np.max(stock_prices)
x,y=np.where(stock_prices==max)
high=stock_prices[x,y]
print(f"Highest price recorded : {high} at Day {x} , company {y}")


[312.2        314.4        294.5        350.76666667 317.46666667]
Highest price recorded : [495] at Day [2] , company [2]


In [7]:

for row in range(len(stock_prices)):
    lst=[]
    for col in range(len(stock_prices[row])):
        if (stock_prices[row][col]<200):
            lst.append(stock_prices[row][col])

    if(len(lst)!=0):
        print(f"Day {row} : {lst}")
            

Day 0 : [103]
Day 1 : [144]
Day 2 : [115]
Day 3 : [196]
Day 4 : [102]
Day 5 : [129]
Day 6 : [123]
Day 8 : [157]
Day 9 : [193, 181]
Day 10 : [175, 100, 148]
Day 11 : [102]
Day 12 : [187]
Day 13 : [180]
Day 15 : [128]
Day 16 : [193, 184, 197]
Day 17 : [161]
Day 18 : [135]
Day 20 : [136]
Day 22 : [109]
Day 23 : [169, 158]
Day 24 : [153, 145]
Day 25 : [143]


In [9]:
#Problem 2

arr=np.random.randint(1,50,(6,3))
print(arr)
sum=np.sum(arr,axis=0)
print(f"Total resources needed (tons) : Oxygen {sum[0]} Water {sum[1]} Food {sum[2]}")

[[29 13 34]
 [ 4 10 11]
 [43  9 48]
 [13 33 26]
 [ 9 26 16]
 [43  6 21]]
Total resources needed (tons) : Oxygen 141 Water 97 Food 156


In [11]:
import numpy as np
max=np.max(arr)
x,y=np.where(arr==max)
d={0:"Oxygen",1:"Water",2:"Food"}
y=int(y[0])
print(f"Highest consumption in a month : {d[y]} ({arr[x,y]} tons in month {y})")

Highest consumption in a month : Food ([48] tons in month 2)


In [13]:
sdev=np.std(arr,axis=0)
print(f"Standard deviation of consumption: Oxygen: {sdev[0]:.1f}, Water: {sdev[1]:.1f}, Food: {sdev[2]:.1f}")

Standard deviation of consumption: Oxygen: 15.8, Water: 9.9, Food: 12.2


In [15]:
transposed_matrix=arr.transpose()
print(transposed_matrix)

[[29  4 43 13  9 43]
 [13 10  9 33 26  6]
 [34 11 48 26 16 21]]


In [17]:
#problem3
points = np.array([
    [10, 25, 30, 22, 12, 18, 26, 32, 24, 29],
    [20, 15, 12, 28, 24, 26, 30, 18, 22, 25],
    [35, 30, 32, 40, 28, 34, 29, 31, 26, 37],
    [12, 18, 20, 15, 22, 14, 19, 21, 23, 17],
    [28, 26, 27, 25, 30, 29, 35, 32, 31, 38]
])

print("Average points per game: ",np.average(points,axis=1))

Average points per game:  [22.8 22.  32.2 18.1 30.1]


In [24]:
total_points=np.sum(points,axis=1)
#Best-performing player: Player 3 (Total: 322 points)
#Worst-performing player: Player 4 (Total: 181 points)
max=np.max(total_points)
min=np.min(total_points)
x=np.where(total_points==min)
y=np.where(total_points==max)
new_max=y[0]
new_min=x[0]
print(f"Best-performing player: Player {new_max} (Total: {max} points)")
print(f"Worst-performing player: Player {new_min} (Total: {min} points)")

Best-performing player: Player [2] (Total: 322 points)
Worst-performing player: Player [3] (Total: 181 points)


In [52]:
mask=points>30
print(points[mask])


[32 35 32 40 34 31 37 35 32 31 38]


In [54]:
for i in points:
    print(i[mask])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed